---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - centos-7
      - rocky-8
      - debian-9
      - debian-10
      - ubuntu-1804
      - ubuntu-2004
    puppet:
      - puppet6
      - puppet7
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
Rakefile:
  changelog_project: puppet-module-cachefilesd
