---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - el7
      - el8
      - ---el9
      - debian-10
      - ubuntu-2004
    puppet:
      - puppet7
      - puppet8
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
Rakefile:
  changelog_project: puppet-module-cachefilesd
